language: node_js

node_js:
  - '6'

before_install:
  - set -e

script:
  - 'npm run ci:lint'
  - 'npm run ci:test'

after_success:
  - 'npm run ci:send-coverage'
  - 'npm run build'
  - 'make prepare-site'
  - 'export ACCP_URL=`npm run deploy:accp:ci | grep "https://" | tr -d "[:space:]"`'
  - 'npm run ci:comment-url'

notifications:
  email: false
